-- SQL script to create customers table
CREATE TABLE customers (
    customer_id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    address VARCHAR(255),
    city VARCHAR(50),
    state VARCHAR(50),
    zip_code VARCHAR(10),
    country VARCHAR(50),
    phone_number VARCHAR(20),
    alternate_phone_number VARCHAR(20),
    email VARCHAR(100) UNIQUE,
    alternate_email VARCHAR(100),
    date_of_birth DATE,
    gender VARCHAR(20),
    marital_status VARCHAR(20),
    occupation VARCHAR(50),
    income_level VARCHAR(20),
    driver_license_number VARCHAR(20),
    social_security_number VARCHAR(20),
    passport_number VARCHAR(20),
    policy_start_date DATE,
    policy_end_date DATE,
    preferred_contact_method VARCHAR(20),
    email_opt_in BOOLEAN DEFAULT FALSE,
    sms_opt_in BOOLEAN DEFAULT FALSE,
    phone_call_opt_in BOOLEAN DEFAULT FALSE
);