-- SQL script to insert multiple customer records
INSERT INTO customers (
    first_name,
    last_name,
    middle_name,
    address,
    city,
    state,
    zip_code,
    country,
    phone_number,
    alternate_phone_number,
    email,
    alternate_email,
    date_of_birth,
    gender,
    marital_status,
    occupation,
    income_level,
    driver_license_number,
    social_security_number,
    passport_number,
    policy_start_date,
    policy_end_date,
    preferred_contact_method,
    email_opt_in,
    sms_opt_in,
    phone_call_opt_in
) VALUES (
    'John',
    'Smith',
    'Robert',
    '123 Main St',
    'Los Angeles',
    'CA',
    '90001',
    'USA',
    '555-123-4567',
    '555-987-6543',
    'john.smith@email.com',
    'john.r.smith@email.com',
    '1985-03-15',
    'Male',
    'Married',
    'Software Engineer',
    'High',
    'DL123456789',
    '123-45-6789',
    'P123456789',
    '2024-01-01',
    '2025-01-01',
    'Email',
    TRUE,
    FALSE,
    FALSE
);

-- Multiple records insert
INSERT INTO customers (
    first_name,
    last_name,
    middle_name,
    address,
    city,
    state,
    zip_code,
    country,
    phone_number,
    alternate_phone_number,
    email,
    alternate_email,
    date_of_birth,
    gender,
    marital_status,
    occupation,
    income_level,
    driver_license_number,
    social_security_number,
    passport_number,
    policy_start_date,
    policy_end_date,
    preferred_contact_method,
    email_opt_in,
    sms_opt_in,
    phone_call_opt_in
) VALUES 
(
    'Sarah',
    'Johnson',
    'Marie',
    '456 Oak Ave',
    'New York',
    'NY',
    '10001',
    'USA',
    '555-234-5678',
    '555-876-5432',
    'sarah.johnson@email.com',
    'sarah.m.johnson@email.com',
    '1990-07-22',
    'Female',
    'Single',
    'Doctor',
    'Very High',
    'DL987654321',
    '987-65-4321',
    'P987654321',
    '2024-01-01',
    '2025-01-01',
    'Phone',
    TRUE,
    TRUE,
    TRUE
),
(
    'Michael',
    'Brown',
    'James',
    '789 Pine St',
    'Chicago',
    'IL',
    '60601',
    'USA',
    '555-345-6789',
    '555-765-4321',
    'michael.brown@email.com',
    'michael.j.brown@email.com',
    '1988-11-30',
    'Male',
    'Divorced',
    'Teacher',
    'Medium',
    'DL456789123',
    '456-78-9123',
    'P456789123',
    '2024-01-01',
    '2025-01-01',
    'SMS',
    FALSE,
    TRUE,
    FALSE
);